### ISSUE TITLE
bulletin file ingest file *uniquifier* doesn't.

### ISSUE THREAD

**Issue by petersilva** [MetPX/Sundew#1]
When ingesting WMO bulletins via the bulletin-file receiver, the ingest file name is discarded and replaced by one generated by sundew.  There is a five digit number created that is supposed to make the file ingested unique.  This worked great when we had one server running the ingestor, but now that we have four, and on startup theyall start a counter to 99999 at zero, and many files arrive with the same name, we have many clashes.

After some discussion, the conclusion is to build a new version of sundew with that five digit number assignement logic replaced by calculation of a 16-bit CRC (which should still be a five digit decimal number.)  That should improve things a lot.

Noureddine has volunteered to work on this next week, Just added Jun and I so we get mail when it progresses.

**Comment by petersilva** [comment]
http://crcmod.sourceforge.net/crcmod.html

found the documentation for CRC-16 module in python, that is available in Debian/ubuntu  repos.

**Comment by habilinour** [comment]
The code has been updated. The sequence number was replaced by a CRC16 code. The code has been tested on dev. Other tests will follow on stage..

**Comment by habilinour** [comment]
Tests will be done on stage before closing the issue

**Comment by petersilva** [comment]
Great!

**Comment by petersilva** [comment]
This got implemented and solved the problems we were having.
Great job, Noureddine.
